[project]
authors = ["timosarkar <timosarkartimo@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "qasm"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.5.0,<25"
pennylane = ">=0.37.0,<0.38"
scikit-learn = ">=1.5.2,<2"
safetensors = ">=0.4.5,<0.5"
matplotlib = ">=3.9.3,<4"
